site_title = "MyArxiv"
limit_days = 30
cache_url = "https://github.com/NineLivesCat/DailyArxiv/cache.json"

[[sources]]
limit = 300
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 300
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 300
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 300
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 300
category = "cs.MA"
title = "Multiagent Systems"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
